### ISSUE TITLE
AdobeAcrobatDcUpdateInfoProvider.py failure with AutoPkg 2.0RC1/Catalina

### ISSUE THREAD

**Issue by jazzace** [autopkg/novaksam-recipes#45]
A `-vv` run of AdobeAcrobatDCUpdates.download using AutoPkg 2.0RC1, Python 3.7 and running under macOS Catalina 10.15.1 generates the following output:
```
WARNING: /Users/tech/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes/Processors/AdobeAcrobatDcUpdateInfoProvider.py: No module named 'urllib2'
Traceback (most recent call last):
  File "/Users/tech/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes/Processors/AdobeAcrobatDcUpdateInfoProvider.py", line 28, in <module>
    from urllib.parse import urlopen  # For Python 3
ImportError: cannot import name 'urlopen' from 'urllib.parse' (/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/urllib/parse.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 820, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tech/Library/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes/Processors/AdobeAcrobatDcUpdateInfoProvider.py", line 30, in <module>
    from urllib2 import urlopen  # For Python 2
ModuleNotFoundError: No module named 'urllib2'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 820, in get_processor
    _tmp = imp.load_source(processor_name, processor_filename)
Failed.
Receipt written to /tmp/receipts/AdobeAcrobatDCUpdates-receipt-20191209-091050.plist

The following recipes failed:
    AdobeAcrobatDCUpdates.download
        Unable to import 'com.github.autopkg.novaksam-recipes.Processors/AdobeAcrobatDcUpdateInfoProvider', likely due to syntax or Python error.
```

**Comment by novaksam** [comment]
Looks like I need to update it to use https://docs.python.org/3/library/urllib.request.html 

The mac I usually use for working on autopkg stuff is occupied with a different task at the moment, but this shouldn't be too hard to fix.

**Comment by novaksam** [comment]
I believe this is fixed with https://github.com/autopkg/novaksam-recipes/commit/df1b32d96e6dd08930580a1b20449d78e614468e
