### ISSUE TITLE
WacomIntuos.download Processor URLTextSearcher Error 

### ISSUE THREAD

**Issue by Darks7ar** [autopkg/novaksam-recipes#60]
The following recipes failed:
    com.github.novaksam.download.WacomIntuos
        Error in com.github.novaksam.download.WacomIntuos: Processor: URLTextSearcher: Error: No match found on URL: https://www.wacom.com/en-us/support/product-support/drivers

```URLTextSearcher
{'Input': {'re_pattern': '(http://cdn.wacom.com/u/productsupport/drivers/mac/professional/WacomTablet_+[0-9].+[0-9].+[0-9]*-*[0-9].dmg)',
           'url': 'https://www.wacom.com/en-us/support/product-support/drivers'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 465, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://www.wacom.com/en-us/support/product-support/drivers
  File "/Library/AutoPkg/autopkglib/__init__.py", line 658, in process
    self.env = processor.process()
```

**Comment by Darks7ar** [comment]
Created PR #61 to fix this issue.
